-- 设备告警记录表
CREATE TABLE IF NOT EXISTS `xmt_device_alerts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '告警ID',
  `device_id` int(11) unsigned NOT NULL COMMENT '设备ID',
  `device_code` varchar(50) NOT NULL DEFAULT '' COMMENT '设备编码',
  `merchant_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '商家ID',
  `alert_type` varchar(50) NOT NULL DEFAULT '' COMMENT '告警类型 offline|low_battery|fault|timeout',
  `alert_level` enum('info','warning','error','critical') NOT NULL DEFAULT 'warning' COMMENT '告警级别',
  `alert_title` varchar(200) DEFAULT NULL COMMENT '告警标题',
  `alert_message` text COMMENT '告警内容',
  `alert_data` json DEFAULT NULL COMMENT '告警数据',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '告警状态 pending|acknowledged|resolved|ignored',
  `trigger_time` datetime DEFAULT NULL COMMENT '触发时间',
  `resolve_time` datetime DEFAULT NULL COMMENT '解决时间',
  `resolve_user_id` int(11) DEFAULT NULL COMMENT '解决者ID',
  `resolve_note` varchar(500) DEFAULT NULL COMMENT '解决备注',
  `notification_sent` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已发送通知',
  `notification_channels` json DEFAULT NULL COMMENT '通知渠道',
  `notification_logs` json DEFAULT NULL COMMENT '通知日志',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_device_code` (`device_code`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_alert_type` (`alert_type`),
  KEY `idx_alert_level` (`alert_level`),
  KEY `idx_status` (`status`),
  KEY `idx_trigger_time` (`trigger_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备告警记录表';
