-- 素材表
CREATE TABLE IF NOT EXISTS `xmt_materials` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '素材ID',
  `type` enum('VIDEO','AUDIO','TRANSITION','TEXT_TEMPLATE','IMAGE','MUSIC') NOT NULL COMMENT '素材类型',
  `name` varchar(200) NOT NULL COMMENT '素材名称',
  `category_id` int(11) DEFAULT NULL COMMENT '分类ID',
  `file_url` varchar(500) NOT NULL COMMENT '文件URL',
  `thumbnail_url` varchar(500) DEFAULT NULL COMMENT '缩略图URL',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小(字节)',
  `duration` int DEFAULT NULL COMMENT '时长(秒)',
  `metadata` json DEFAULT NULL COMMENT '元数据',
  `tags` json DEFAULT NULL COMMENT '标签',
  `usage_count` int DEFAULT 0 COMMENT '使用次数',
  `weight` int DEFAULT 100 COMMENT '推荐权重',
  `status` tinyint(1) DEFAULT 1 COMMENT '状态 0禁用 1启用 2审核中',
  `audit_status` tinyint(1) DEFAULT 0 COMMENT '审核状态 0待审核 1通过 2拒绝',
  `audit_message` text COMMENT '审核信息',
  `creator_id` int(11) DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_type` (`type`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_status` (`status`),
  KEY `idx_audit_status` (`audit_status`),
  KEY `idx_usage_count` (`usage_count`),
  KEY `idx_weight` (`weight`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='素材表';