CREATE TABLE `anomaly_alerts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '异常ID',
  `merchant_id` int(11) unsigned DEFAULT NULL COMMENT '商家ID',
  `type` varchar(50) NOT NULL COMMENT '异常类型',
  `severity` enum('CRITICAL','HIGH','MEDIUM','LOW') DEFAULT 'MEDIUM' COMMENT '严重等级',
  `metric_name` varchar(100) DEFAULT NULL COMMENT '指标名称',
  `current_value` decimal(15,2) DEFAULT NULL COMMENT '当前值',
  `expected_value` decimal(15,2) DEFAULT NULL COMMENT '期望值',
  `deviation` decimal(10,2) DEFAULT NULL COMMENT '偏差百分比',
  `possible_causes` json DEFAULT NULL COMMENT '可能原因',
  `status` enum('DETECTED','NOTIFIED','HANDLING','RESOLVED','IGNORED') DEFAULT 'DETECTED' COMMENT '处理状态',
  `notified_at` datetime DEFAULT NULL COMMENT '通知时间',
  `resolved_at` datetime DEFAULT NULL COMMENT '解决时间',
  `handle_notes` text COMMENT '处理备注',
  `extra_data` json DEFAULT NULL COMMENT '额外数据',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_type` (`type`),
  KEY `idx_severity` (`severity`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='异常预警表';
